modelName: sphere@hardsphere
nContrib: 300
modelDType: default
fitParameterLimits:
  radius:
  - 3.14
  - 314
staticParameters:
  sld: 33.4
  sld_solvent: 0
maxIter: 100000
convCrit: 1
nRep: 10
nCores: 5
